#include <p32xxxx.h>
#include <inttypes.h>
#include <LED.h>
#include <GPIODrv.h>


void LED_init(){	// All of them.
	LEDUSER_TRISbits.LEDUSER_TRISPIN = 0;	// Set to output
	LEDUSBINT_TRISbits.LEDUSBINT_TRISPIN = 0;
	LEDUSBUART_OUT_TRISbits.LEDUSBUART_OUT_TRISPIN = 0;
	LEDUSBUART_IN_TRISbits.LEDUSBUART_IN_TRISPIN = 0;
	LEDUSBPROG_OUT_TRISbits.LEDUSBPROG_OUT_TRISPIN = 0;
	LEDUSBPROG_IN_TRISbits.LEDUSBPROG_IN_TRISPIN = 0;
}

void LED_setState(uint8_t state){
	if (state){
		LEDUSER_LATbits.LEDUSER_LATPIN = 1;
	}
	else{
		LEDUSER_LATbits.LEDUSER_LATPIN = 0;
	}
}

void LED_toggle(){
	LEDUSER_LATINV = LEDUSER_MASK;
}


// Debug & timing LEDs
void LED_USBINT_toggle(){
	LEDUSBINT_LATINV = LEDUSBINT_MASK;
}
void LED_USBUART_OUT_toggle(){
	LEDUSBUART_OUT_LATINV = LEDUSBUART_OUT_MASK;
}
void LED_USBUART_IN_toggle(){
	LEDUSBUART_IN_LATINV = LEDUSBUART_IN_MASK;
}
void LED_USBPROG_OUT_toggle(){
	LEDUSBPROG_OUT_LATINV = LEDUSBPROG_OUT_MASK;
}
void LED_USBPROG_IN_toggle(){
	LEDUSBPROG_IN_LATINV = LEDUSBPROG_IN_MASK;
}
